spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/logistics_user
spring.datasource.username=postgres
spring.datasource.password=263160

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.data.redis.host=localhost
spring.data.redis.port=6379


eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone = http://localhost:8761/eureka