spring.application.name=payment_service
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/logistics_payment
spring.datasource.username=postgres
spring.datasource.password=263160

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

razorpay.key.id=rzp_test_T2N2GAwPRATnKt
razorpay.key.secret=Zt1RKPu4Yy2wBCKDnwnDNb1O

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
